### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by bugwelle** [bugwelle/cpp-starter-project#1]
- [x]  Sphinx User Documentation
 - [x]  `range-v3`
 - [x]  cppcheck in cmake
 - [x]  shellcheck in CI
 - [ ]  CI
   - [ ] AppVeyor
   - [ ] GitLabCI
   - [ ] TravisCI 
 - [ ]  CD (Bintray)
 - [ ]  Code Coverage
